# Clase 1
## Ejercicio 1

In [1]:
import numpy as np

![alt text](../img/vector_norms.jpg "Title")

In [2]:
lista = np.random.randn(3,3)

In [3]:
lista


array([[-0.86015437,  0.87635955,  1.00634389],
       [ 0.63411901,  1.03352417,  1.11311987],
       [ 1.2238965 , -0.2969407 ,  1.82851655]])

In [4]:
def p_norms(l,p):
    res = (np.sum(np.abs(l)**p, axis=1)**(1/p))
    return res

In [5]:
p_norms(lista,2)

array([1.58763964, 1.64599968, 2.22026332])

In [6]:
def norm_inf(l):
    return np.max(np.sum(np.abs(l),axis=1))
    

In [7]:
a = np.array([[4,5,6],[7,8,9],[1,2,3]])

In [8]:
a

array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [9]:
norm_inf(a)

24

In [10]:
a.shape[0]

3

## Ejercicio 2

In [11]:
def sorting(l):
    p_rows = p_norms(l,2)
    print(p_rows)
    p_rows_index = np.argsort(p_rows)[::-1]
    print(p_rows_index)
    #p_sort = np.sort(p_rows)[::-1]
    new_matrix = []
    #print(p_rows_index)
    for i in p_rows_index:
        new_matrix.append(l[:][i])
    return(new_matrix)

In [12]:
sorting(a)

[ 8.77496439 13.92838828  3.74165739]
[1 0 2]


[array([7, 8, 9]), array([4, 5, 6]), array([1, 2, 3])]

## Ejercicio 3

In [33]:
class Indexing:
    def __init__(self, users_id):
        self.users_id = users_id
        self.users_idx = list(range(len(users_id)))
    
    def get_users_id(self):
        return(self.users_id)
        
    def get_users_idx(self):
        return(self.users_idx)
    
    def id2idx(self, user_id):
        return(self.users_id[user_id])
    
    def idx2id(self, user_idx):
        return(self.users_id[user_idx])
        

In [34]:
index = Indexing([-1, 4, 5, -1, -1, -1, -1, -1, -1, -1, 3, -1, 1, -1, 2, 0])
print(index.get_users_id())
print(index.get_users_idx())

[-1, 4, 5, -1, -1, -1, -1, -1, -1, -1, 3, -1, 1, -1, 2, 0]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [37]:
index.id2idx(5)

-1

In [38]:
index.idx2id(15)

0

### Ejercicio 4

In [17]:
class Metricas:
    def __init__(self, truth, prediction):
        self.truth = truth
        self.prediction = prediction
    
    def boolean_list(self):
            l = []
            for i in range (0,len(self.truth)):
                if (self.truth[i]==1) & (self.prediction[i]==1):
                    l.append("TP")
                elif (self.truth[i]==0) & (self.prediction[i]==0):
                    l.append("TN")
                elif (self.truth[i]==1) & (self.prediction[i]==0):
                    l.append("FN")
                else:
                    l.append("FP")
            return (l)

    def variables(self):
        bool_l = self.boolean_list()
        l_variables = ["TP", "TN", "FN", "FP"]
        l_variables_count = []
        for i in l_variables:
            l_variables_count.append(bool_l.count(i))
        return (l_variables_count)
        
    def precision(self):
        l = self.variables()
        res = l[0] / (l[0] + l[3])
        return (res)
    
    def recall(self):
        l = self.variables()
        res = l[0] / (l[0] + l[2])
        return (res)
    
    def accuracy(self):
        l = self.variables()
        res = (l[0] + l[1])/ (l[0] + l[1] + l[2] + l[3])
        return (res)

In [18]:
truth = np.array([1,1,0,1])
prediction = np.array([1,0,0,1])


In [19]:
m = Metricas(truth, prediction)
print(m.boolean_list())
print(m.variables())
print(m.precision())
print(m.recall())
print(m.accuracy())

['TP', 'FN', 'TN', 'TP']
[2, 1, 1, 0]
1.0
0.6666666666666666
0.75


## Ejercicio 6