# Clase 1
## Ejercicio 1

In [1]:
import numpy as np

![alt text](../img/vector_norms.jpg "Title")

In [37]:
lista = np.random.randn(3,3)

In [38]:
lista


array([[-1.31220907,  1.37229137, -0.60529516],
       [ 0.79298074,  0.29351005,  0.09946025],
       [ 0.8650505 , -1.97924601, -1.72060294]])

In [39]:
def p_norms(l,p):
    res = (np.sum(np.abs(l)**p, axis=1)**(1/p))
    return res

In [40]:
norma(lista,2)

array([1.99285185, 0.85138648, 2.76155783])

In [57]:
def norm_inf(l):
    return np.max(np.sum(np.abs(l),axis=1))
    

In [58]:
a = np.array([[7,8,9],[4,5,6],[1,2,3]])

In [59]:
a

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [60]:
norm_inf(a)

24