# Clase 1
## Ejercicio 1

In [1]:
import numpy as np

![alt text](../img/vector_norms.jpg "Title")

In [2]:
lista = np.random.randn(3,3)

In [3]:
lista


array([[ 0.82712041, -2.30048341, -0.53620039],
       [-0.25413198,  0.55844981,  1.96051747],
       [ 0.76421323, -0.09806653, -1.13076032]])

In [4]:
def p_norms(l,p):
    res = (np.sum(np.abs(l)**p, axis=1)**(1/p))
    return res

In [97]:
p_norms(lista,2)

array([2.50277105, 2.05428284, 1.36830472])

In [98]:
def norm_inf(l):
    return np.max(np.sum(np.abs(l),axis=1))
    

In [99]:
a = np.array([[4,5,6],[7,8,9],[1,2,3]])

In [100]:
a

array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [101]:
norm_inf(a)

24

In [102]:
a.shape[0]

3

## Ejercicio 2

In [103]:
def sorting(l):
    p_rows = p_norms(l,2)
    print(p_rows)
    p_rows_index = np.argsort(p_rows)[::-1]
    print(p_rows_index)
    #p_sort = np.sort(p_rows)[::-1]
    new_matrix = []
    #print(p_rows_index)
    for i in p_rows_index:
        new_matrix.append(l[:][i])
    return(new_matrix)

In [104]:
sorting(a)

[ 8.77496439 13.92838828  3.74165739]
[1 0 2]


[array([7, 8, 9]), array([4, 5, 6]), array([1, 2, 3])]

## Ejercicio 3

In [151]:
class Indexing:
    def __init__(self, users_id):
        self.users_id = users_id
        self.users_idx = list(range(len(users_id)))
    
    def get_users_id(self):
        return(self.users_id)
        
    def get_users_idx(self):
        return(self.users_idx)
    
    def id2idx(self, user_id):
        return(self.users_id[user_id])
    
    def idx2id(self, user_idx):
        return(self.users_id[user_idx])
        

In [152]:
index = Indexing([-1, 4, 5, -1, -1, -1, -1, -1, -1, -1, 3, -1, 1, -1, 2, 0])
print(index.get_users_id())
print(index.get_users_idx())

[-1, 4, 5, -1, -1, -1, -1, -1, -1, -1, 3, -1, 1, -1, 2, 0]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [155]:
index.id2idx(3)

-1

In [154]:
index.idx2id(4)

-1